import { useEffect, useState } from "react";
import Button from "../../../components/common/Button";
import Modal from "../../../components/common/Modal";
import Table from "../../../components/common/Table";
import { api } from "../../../lib/api";
import { StatusBadge } from "../shared/adminShared";

const configs = {
  category: { title: "Categories", fields: [["name", "Category name"], ["image", "Image URL"]] },
  brand: { title: "Brands", fields: [["name", "Brand name"]], categories: true },
  size: { title: "Sizes", fields: [["name", "Size name"]], categories: true },
  color: { title: "Colors", fields: [["name", "Color name"], ["hexCode", "Hex code"]], active: true },
  banner: { title: "Banners", fields: [["title", "Title"], ["description", "Description"], ["image", "Image URL"], ["link", "Link URL"]], active: true },
  offer: { title: "Offers", fields: [["title", "Title"], ["description", "Description"], ["discount", "Discount"], ["startDate", "Start date", "date"], ["endDate", "End date", "date"]], active: true },
  coupon: { title: "Coupons", fields: [["code", "Coupon code"], ["discountValue", "Discount value", "number"], ["minimumAmount", "Minimum amount", "number"], ["expiryDate", "Expiry date", "date"]], active: true },
};
const base = (resource) => ({ ...(resource === "coupon" ? { discountType: "percentage" } : {}), isActive: true, categories: [] });
const MasterDataManager = ({ resource }) => {
  const config = configs[resource]; const [items, setItems] = useState([]), [categories, setCategories] = useState([]), [form, setForm] = useState(base(resource)), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const data = await api(`/admin/${resource}`); setItems(data); if (config.categories) setCategories(await api("/admin/category")); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [resource]);
  const save = async (event) => { event.preventDefault(); try { const payload = { ...form }; ["discount", "discountValue", "minimumAmount"].forEach((key) => { if (payload[key] !== undefined) payload[key] = Number(payload[key]); }); await api(editing ? `/admin/${resource}/${editing._id}` : `/admin/${resource}`, { method: editing ? "PUT" : "POST", body: JSON.stringify(payload) }); setOpen(false); load(); } catch (e) { setError(e.message); } };
  const remove = async (id) => { if (!window.confirm("Delete this item?")) return; try { await api(`/admin/${resource}/${id}`, { method: "DELETE" }); load(); } catch (e) { setError(e.message); } };
  const headers = [resource === "color" ? "Color" : config.title.slice(0, -1), ...(config.categories ? ["Categories"] : []), ...(config.active ? ["Status"] : []), "Actions"];
  const rows = items.map((item) => [resource === "color" ? <span className="flex items-center gap-2" key={item._id}><i className="h-5 w-5 rounded-full border" style={{ background: item.hexCode }}/>{item.name} ({item.hexCode})</span> : item.name || item.title || item.code, ...(config.categories ? [item.categories?.map((category) => category.name || category).join(", ") || "No categories"] : []), ...(config.active ? [<StatusBadge key={`${item._id}-status`} value={item.isActive ? "Active" : "Inactive"} />] : []), <div key={`${item._id}-actions`} className="flex gap-2"><Button variant="secondary" className="px-3 py-1 text-xs" onClick={() => { setEditing(item); setForm({ ...base(resource), ...item, categories: item.categories?.map((category) => category._id || category) || [], expiryDate: item.expiryDate?.slice(0, 10) || "", startDate: item.startDate?.slice(0, 10) || "", endDate: item.endDate?.slice(0, 10) || "" }); setOpen(true); }}>Edit</Button><Button variant="ghost" className="px-3 py-1 text-xs text-rose-600" onClick={() => remove(item._id)}>Delete</Button></div>]);
  return <div className="space-y-4"><div className="flex items-center justify-between"><h2 className="font-display text-2xl font-semibold text-primary-600">{config.title}</h2><Button onClick={() => { setEditing(null); setForm(base(resource)); setOpen(true); }}>Add {config.title.slice(0, -1)}</Button></div>{error && <p className="rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p>}{loading ? <p>Loading {config.title.toLowerCase()}...</p> : <Table headers={headers} rows={rows} emptyMessage={`No ${config.title.toLowerCase()} found.`}/>}<Modal open={open} title={`${editing ? "Edit" : "Add"} ${config.title.slice(0, -1)}`} onClose={() => setOpen(false)}><form className="grid gap-3" onSubmit={save}>{config.fields.map(([key, label, type = "text"]) => key === "description" ? <textarea key={key} placeholder={label} value={form[key] || ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="rounded-xl border p-2"/> : <input key={key} required={key === "name" || key === "title" || key === "code"} type={type} placeholder={label} value={form[key] || ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="rounded-xl border p-2"/>)}{resource === "coupon" && <select value={form.discountType} onChange={(e) => setForm({ ...form, discountType: e.target.value })} className="rounded-xl border p-2"><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select>}{config.categories && <fieldset className="rounded-xl border p-3"><legend className="px-1 text-sm font-semibold">Categories</legend>{categories.map((category) => <label key={category._id} className="mr-4 inline-flex items-center gap-2 text-sm"><input type="checkbox" checked={form.categories.includes(category._id)} onChange={(e) => setForm({ ...form, categories: e.target.checked ? [...form.categories, category._id] : form.categories.filter((id) => id !== category._id) })}/>{category.name}</label>)}</fieldset>}{config.active && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })}/> Active</label>}<div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit">Save</Button></div></form></Modal></div>;
};
export default MasterDataManager;
