import { useEffect, useState } from "react";
import Button from "../../../components/common/Button";
import Modal from "../../../components/common/Modal";
import Table from "../../../components/common/Table";
import { api } from "../../../lib/api";
import { StatusBadge, panelClass } from "../shared/adminShared";

const blank = { name: "", details: "", category: "", brand: "", size: "", color: "", mrp: "", saleprice: "", quantity: "", image: "", isActive: true };
const AdminProducts = () => {
  const [products, setProducts] = useState([]), [lists, setLists] = useState({ category: [], brand: [], size: [], color: [] }), [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [error, setError] = useState("");
  const load = async () => { try { const [products, category, brand, size, color] = await Promise.all([api("/admin/products"), ...["category", "brand", "size", "color"].map((x) => api(`/admin/${x}`))]); setProducts(products); setLists({ category, brand, size, color }); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, []);
  const set = (key, value) => setForm((old) => key === "category" ? { ...old, category: value, brand: "", size: "" } : { ...old, [key]: value });
  const save = async (event) => { event.preventDefault(); try { await api(editing ? `/admin/products/${editing._id}` : "/admin/products", { method: editing ? "PUT" : "POST", body: JSON.stringify({ ...form, mrp: +form.mrp, saleprice: +form.saleprice, quantity: +form.quantity }) }); setOpen(false); load(); } catch (e) { setError(e.message); } };
  const action = async (url, method = "PUT", body) => { try { await api(url, { method, body: body && JSON.stringify(body) }); load(); } catch (e) { setError(e.message); } };
  const linked = (kind) => form.category ? lists[kind].filter((x) => x.categories?.some((c) => String(c._id || c) === form.category)) : lists[kind];
  const rows = products.map((p) => [<div key={p._id}><b>{p.name}</b><p className="text-xs text-slate-500">{p.category?.name} · {p.brand?.name || "No brand"}</p></div>, `$${p.saleprice}`, p.quantity, p.vendor?.name || "Admin", <StatusBadge value={p.approvalStatus} />, <div className="flex flex-wrap gap-1" key={`${p._id}x`}>{p.approvalStatus !== "approved" && <Button className="px-2 py-1 text-xs" onClick={() => action(`/admin/products/${p._id}/approve`)}>Approve</Button>}{p.approvalStatus !== "rejected" && <Button variant="secondary" className="px-2 py-1 text-xs" onClick={() => { const reason = prompt("Rejection reason"); if (reason !== null) action(`/admin/products/${p._id}/reject`, "PUT", { reason }); }}>Reject</Button>}<Button variant="ghost" className="px-2 py-1 text-xs" onClick={() => { setEditing(p); setForm({ ...blank, ...p, category: p.category?._id || "", brand: p.brand?._id || "", size: p.size?._id || "", color: p.color?._id || "" }); setOpen(true); }}>Edit</Button><Button variant="ghost" className="px-2 py-1 text-xs text-red-600" onClick={() => action(`/admin/products/${p._id}`, "DELETE")}>Delete</Button></div>]);
  return <div className="space-y-4"><div className="flex justify-between"><h2 className="font-display text-2xl font-semibold text-primary-600">Manage Products</h2><Button onClick={() => { setEditing(null); setForm(blank); setOpen(true); }}>Add Product</Button></div>{error && <p className="text-red-600">{error}</p>}<p className={panelClass}>Admin products are approved immediately; vendor products need an approval action.</p><Table headers={["Product", "Price", "Stock", "Vendor", "Status", "Actions"]} rows={rows} emptyMessage="No products found."/><Modal open={open} title={editing ? "Edit Product" : "Add Product"} onClose={() => setOpen(false)}><form className="grid gap-3" onSubmit={save}><input required placeholder="Product name" value={form.name} onChange={(e) => set("name", e.target.value)} className="rounded-xl border p-2"/><textarea placeholder="Description" value={form.details} onChange={(e) => set("details", e.target.value)} className="rounded-xl border p-2"/><select required value={form.category} onChange={(e) => set("category", e.target.value)} className="rounded-xl border p-2"><option value="">Category</option>{lists.category.map((x) => <option key={x._id} value={x._id}>{x.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><select value={form.brand} onChange={(e) => set("brand", e.target.value)} className="rounded-xl border p-2"><option value="">Brand</option>{linked("brand").map((x) => <option key={x._id} value={x._id}>{x.name}</option>)}</select><select value={form.size} onChange={(e) => set("size", e.target.value)} className="rounded-xl border p-2"><option value="">Size</option>{linked("size").map((x) => <option key={x._id} value={x._id}>{x.name}</option>)}</select></div><div className="grid grid-cols-3 gap-3">{[["mrp", "MRP"], ["saleprice", "Sale price"], ["quantity", "Quantity"]].map(([key, label]) => <input key={key} required min="0" type="number" placeholder={label} value={form[key]} onChange={(e) => set(key, e.target.value)} className="rounded-xl border p-2"/>)}</div><select value={form.color} onChange={(e) => set("color", e.target.value)} className="rounded-xl border p-2"><option value="">Color</option>{lists.color.map((x) => <option key={x._id} value={x._id}>{x.name}</option>)}</select><input placeholder="Image URL" value={form.image} onChange={(e) => set("image", e.target.value)} className="rounded-xl border p-2"/><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit">Save</Button></div></form></Modal></div>;
};
export default AdminProducts;
